using System;

internal static partial class Settings
{
    private static readonly String[,] Characters = {
        // control characters
        // 0-31
        { "NUL", "Null character" },
        { "SOH", "Start of Heading" },
        { "STX", "Start of Text" },
        { "ETX", "End of Text" },
        { "EOT", "End of Transmission" },
        { "ENQ", "Enquiry" },
        { "ACK", "Acknowledge" },
        { "BEL", "Bell, Alert" },
        { "BS", "Backspace" },
        { "HT", "Horizontal Tab" },
        { "LF", "Line Feed" },
        { "VT", "Vertical Tabulation" },
        { "FF", "Form Feed" },
        { "CR", "Carriage Return" },
        { "SO", "Shift Out" },
        { "SI", "Shift In" },
        { "DLE", "Data Link Escape" },
        { "DC1", "Device Control One (XON)" },
        { "DC2", "Device Control Two" },
        { "DC3", "Device Control Three (XOFF)" },
        { "DC4", "Device Control Four" },
        { "NAK", "Negative Acknowledge" },
        { "SYN", "Synchronous Idle" },
        { "ETB", "End of Transmission Block" },
        { "CAN", "Cancel" },
        { "EM", "End of medium" },
        { "SUB", "Substitute" },
        { "ESC", "Escape" },
        { "FS", "File Separator" },
        { "GS", "Group Separator" },
        { "RS", "Record Separator" },
        { "US", "Unit Separator" },
        // printable characters
        // 32-127
        { "SP", "Space"},
        { "!", null! },
        { "\"", null! },
        { "#", null! },
        { "$", null! },
        { "%", null! },
        { "&", null! },
        { "'", null! },
        { "(", null! },
        { ")", null! },
        { "*", null! },
        { "+", null! },
        { ",", null! },
        { "-", null! },
        { ".", null! },
        { "/", null! },
        { "0", null! },
        { "1", null! },
        { "2", null! },
        { "3", null! },
        { "4", null! },
        { "5", null! },
        { "6", null! },
        { "7", null! },
        { "8", null! },
        { "9", null! },
        { ":", null! },
        { ";", null! },
        { "<", null! },
        { "=", null! },
        { ">", null! },
        { "?", null! },
        { "@", null! },
        { "A", null! },
        { "B", null! },
        { "C", null! },
        { "D", null! },
        { "E", null! },
        { "F", null! },
        { "G", null! },
        { "H", null! },
        { "I", null! },
        { "J", null! },
        { "K", null! },
        { "L", null! },
        { "M", null! },
        { "N", null! },
        { "O", null! },
        { "P", null! },
        { "Q", null! },
        { "R", null! },
        { "S", null! },
        { "T", null! },
        { "U", null! },
        { "V", null! },
        { "W", null! },
        { "X", null! },
        { "Y", null! },
        { "Z", null! },
        { "[", null! },
        { "\\", null! },
        { "]", null! },
        { "^", null! },
        { "_", null! },
        { "`", null! },
        { "a", null! },
        { "b", null! },
        { "c", null! },
        { "d", null! },
        { "e", null! },
        { "f", null! },
        { "g", null! },
        { "h", null! },
        { "i", null! },
        { "j", null! },
        { "k", null! },
        { "l", null! },
        { "m", null! },
        { "n", null! },
        { "o", null! },
        { "p", null! },
        { "q", null! },
        { "r", null! },
        { "s", null! },
        { "t", null! },
        { "u", null! },
        { "v", null! },
        { "w", null! },
        { "x", null! },
        { "y", null! },
        { "z", null! },
        { "{", null! },
        { "|", null! },
        { "}", null! },
        { "~", null! },
        { "DEL", "Delete"},
        // extended characters
        // 128-255
        { "€", "Euro sign" },
        { "	", "Unused" },
        { "‚", "Single low-9 quotation mark" },
        { "ƒ", "Latin small letter f with hook" },
        { "„", "Double low-9 quotation mark" },
        { "…", "Horizontal ellipsis" },
        { "†", "Dagger" },
        { "‡", "Double dagger" },
        { "ˆ", "Modifier letter circumflex accent" },
        { "‰", "Per mille sign" },
        { "Š", "Latin capital letter S with caron" },
        { "‹", "Single left-pointing angle quotation" },
        { "Œ", "Latin capital ligature OE" },
        { "	", "Unused" },
        { "Ž", "Latin capital letter Z with caron" },
        { "	", "Unused" },
        { "	", "Unused" },
        { "‘", "Left single quotation mark" },
        { "’", "Right single quotation mark" },
        { "“", "Left double quotation mark" },
        { "”", "Right double quotation mark" },
        { "•", "Bullet" },
        { "–", "En dash" },
        { "—", "Em dash" },
        { "˜", "Small tilde" },
        { "™", "Trade mark sign" },
        { "š", "Latin small letter S with caron" },
        { "›", "Single right-pointing angle quotation mark" },
        { "œ", "Latin small ligature oe" },
        { "	", "Unused" },
        { "ž", "Latin small letter z with caron" },
        { "Ÿ", "Latin capital letter Y with diaeresis" },
        { "NBSP", "Non-breaking space" },
        { "¡", "Inverted exclamation mark" },
        { "¢", "Cent sign" },
        { "£", "Pound sign" },
        { "¤", "Currency sign" },
        { "¥", "Yen sign" },
        { "¦", "Pipe, broken vertical bar" },
        { "§", "Section sign" },
        { "¨", "Spacing diaeresis - umlaut" },
        { "©", "Copyright sign" },
        { "ª", "Feminine ordinal indicator" },
        { "«", "Left double angle quotes" },
        { "¬", "Negation" },
        { "SHY", "Soft hyphen" },
        { "®", "Registered trade mark sign" },
        { "¯", "Spacing macron - overline" },
        { "°", "Degree sign" },
        { "±", "Plus-or-minus sign" },
        { "²", "Superscript two - squared" },
        { "³", "Superscript three - cubed" },
        { "´", "Acute accent - spacing acute" },
        { "µ", "Micro sign" },
        { "¶", "Pilcrow sign - paragraph sign" },
        { "·", "Middle dot - Georgian comma" },
        { "¸", "Spacing cedilla" },
        { "¹", "Superscript one" },
        { "º", "Masculine ordinal indicator" },
        { "»", "Right double angle quotes" },
        { "¼", "Fraction one quarter" },
        { "½", "Fraction one half" },
        { "¾", "Fraction three quarters" },
        { "¿", "Inverted question mark" },
        { "À", "Latin capital letter A with grave" },
        { "Á", "Latin capital letter A with acute" },
        { "Â", "Latin capital letter A with circumflex" },
        { "Ã", "Latin capital letter A with tilde" },
        { "Ä", "Latin capital letter A with diaeresis" },
        { "Å", "Latin capital letter A with ring above" },
        { "Æ", "Latin capital letter AE" },
        { "Ç", "Latin capital letter C with cedilla" },
        { "È", "Latin capital letter E with grave" },
        { "É", "Latin capital letter E with acute" },
        { "Ê", "Latin capital letter E with circumflex" },
        { "Ë", "Latin capital letter E with diaeresis" },
        { "Ì", "Latin capital letter I with grave" },
        { "Í", "Latin capital letter I with acute" },
        { "Î", "Latin capital letter I with circumflex" },
        { "Ï", "Latin capital letter I with diaeresis" },
        { "Ð", "Latin capital letter ETH" },
        { "Ñ", "Latin capital letter N with tilde" },
        { "Ò", "Latin capital letter O with grave" },
        { "Ó", "Latin capital letter O with acute" },
        { "Ô", "Latin capital letter O with circumflex" },
        { "Õ", "Latin capital letter O with tilde" },
        { "Ö", "Latin capital letter O with diaeresis" },
        { "×", "Multiplication sign" },
        { "Ø", "Latin capital letter O with slash" },
        { "Ù", "Latin capital letter U with grave" },
        { "Ú", "Latin capital letter U with acute" },
        { "Û", "Latin capital letter U with circumflex" },
        { "Ü", "Latin capital letter U with diaeresis" },
        { "Ý", "Latin capital letter Y with acute" },
        { "Þ", "Latin capital letter THORN" },
        { "ß", "Latin small letter sharp s - ess-zed" },
        { "à", "Latin small letter a with grave" },
        { "á", "Latin small letter a with acute" },
        { "â", "Latin small letter a with circumflex" },
        { "ã", "Latin small letter a with tilde" },
        { "ä", "Latin small letter a with diaeresis" },
        { "å", "Latin small letter a with ring above" },
        { "æ", "Latin small letter ae" },
        { "ç", "Latin small letter c with cedilla" },
        { "è", "Latin small letter e with grave" },
        { "é", "Latin small letter e with acute" },
        { "ê", "Latin small letter e with circumflex" },
        { "ë", "Latin small letter e with diaeresis" },
        { "ì", "Latin small letter i with grave" },
        { "í", "Latin small letter i with acute" },
        { "î", "Latin small letter i with circumflex" },
        { "ï", "Latin small letter i with diaeresis" },
        { "ð", "Latin small letter eth" },
        { "ñ", "Latin small letter n with tilde" },
        { "ò", "Latin small letter o with grave" },
        { "ó", "Latin small letter o with acute" },
        { "ô", "Latin small letter o with circumflex" },
        { "õ", "Latin small letter o with tilde" },
        { "ö", "Latin small letter o with diaeresis" },
        { "÷", "Division sign" },
        { "ø", "Latin small letter o with slash" },
        { "ù", "Latin small letter u with grave" },
        { "ú", "Latin small letter u with acute" },
        { "û", "Latin small letter u with circumflex" },
        { "ü", "Latin small letter u with diaeresis" },
        { "ý", "Latin small letter y with acute" },
        { "þ", "Latin small letter thorn" },
        { "ÿ", "Latin small letter y with diaeresis" },
    };
}